### ISSUE TITLE
[Kubernetes] Create new Prometheus-friendly metric from Fluentd pod logs

### ISSUE THREAD

**Issue by manicole** [fluent/fluent-plugin-prometheus#117]
In Kubernetes, I'd like to create a new metric @type prometheus parsed from Fluentd pod logs.

# Expected Behavior
1. Gather logs from Fluentd pod deployed in namespace opa:
`kubectl logs <fluentd-pod> -n opa`

2. Parse and edit value via a ConfigMap to constitute metrics.
These metrics are formerly displayed at service endpoint, i.e.
`curl https://<fluentd-service-IP>:<fluentd-service-port>/metrics`

# Actual Behavior
After deploying Fluentd container in a pod (as a sidecar of OPA),
installing fluent-plugin-prometheus in this container,
deploying the custom configMap (default endpoint configuration),

`curl https://<fluentd-service-IP>:<fluentd-service-port>/metrics`
shows nothing. I can't find out what I'm missing ...

# Steps to Reproduce the Problem
1. Install Fluentd in a pod as a sidecar container of an OPA container in namespace opa : 
```
        - name: fluentd
          image: fluent/fluentd
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
          - name: FLUENT_UID
            value: "0"
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: fluentd-opa
            mountPath: /fluentd/etc/
```

2. Install fluent-plugin-prometheus in Fluentd container : 
```
kubectl exec -it <pod-name> -n opa -c fluentd /bin/sh
/  # gem install fluent-plugin-prometheus
```

3. Create configMap containing Fluentd configuration in opa namespace
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-opa
  namespace: opa
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <filter kubernetes.var.log.containers.**opa**.log>
      @type prometheus
      <metric>
        name resp_status_counter
        type counter
        desc bla
        key $.log.resp_status
     </metric>
    </filter>

    <match kubernetes.var.log.containers.**opa**.log>
      @type prometheus
    </match>
```
💡 Key is $.log.resp_status because the Fluentd logs to parse (which actually are OPA forwarded logs) are in the form
```
{
	"log":"{
		"client_addr":"10.233.64.1:38700",
		"level":"info",
		"msg":"Sent response.",
		"req_id":12697,
		"req_method":"POST",
		"req_path":"/",
		"resp_body":"{
			"apiVersion":"admission.k8s.io/v1beta1",
			"kind":"AdmissionReview";
			"response":{
				"allowed":true
			}
		}",
		"resp_bytes":94,
		"resp_duration":3.421389,
		"resp_status":200,
		"time":"2019-09-20T13:40:11Z"
	}",
	"stream":"stderr"
}
```

4. Curl Fluentd service endpoint to see supposingly newly created metric : 
`curl https://<fluentd-service-IP>:<fluentd-service-port>/metrics`
(shows nothing).

# Additional Info
Kubernetes v1.14
Fluent-plugin-prometheus v1.6.0
Fluentd v1.3.2
Prometheus-client v0.9.0

# Ideas to solve the issue
* Could it be a namespace problem ?
Fluentd container is deployed in a pod in opa namespace
Fluentd service is deployed in opa namespace
Fluentd ServiceMonitor (CRD from Prometheus operator) is deployed in monitoring namespace and expose logs from Fluentd service to Prometheus
Fluentd ConfigMap is deployed in opa namespace

* Could it be a mount problem ?
`kubectl get configmaps -n opa fluentd-opa -o yaml`

gives, among other informations,

```
    openpolicyagent.org/policy-status: '{"status":"error","error":{"code":"invalid_parameter","message":"error(s)
      occurred while compiling module(s)","errors":[{"code":"rego_parse_error","message":"no
      match found","location":{"file":"opa/fluentd-opa/fluent.conf","row":14,"col":1},"details":{}}]}}'
```

Any help appreciated ! Thanks
