### ISSUE TITLE
aggregated_metrics endpoint only gives partial output

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-plugin-prometheus#175]
### Overview
I have Fluentd set up with multiple workers and multiple plugins. Because of that, there are many Prometheus metrics. 
When I hit the _/metrics_ endpoint for individual workers, there are no issues. However, when I hit the _/aggregated_metrics_ endpoint, I only get partial output -- the output seems to abruptly cut off after a certain point. **Does _/aggregated_metrics_ have a size limit??**

Eg. If I hit the _/aggregated_metrics_ endpoint (`curl http://localhost:24240/aggregated_metrics`), here are the last 3 lines of the resulting output:
```
fluentd_output_status_slow_flush_count{worker_id="0",plugin_id="object:be0",type="null"} 0.0
fluentd_output_status_slow_flush_count{worker_id="0",plugin_id="object:463c",type="relabel"} 0.0
fluentd_output_status_slow_flush_count{worker_id="0",plugin_id="object:465
```
Notice that the last line is abruptly cut off mid-way!

### Prometheus Config
```
<source>
  @type prometheus
  port 24240
  metrics_path /metrics
  aggregated_metrics_path /aggregated_metrics
</source>

<source>
  @type prometheus_output_monitor
</source>
```

### Env Info
- Fluentd: `1.11.2`
- fluent-plugin-prometheus: `1.8.2`
- fluent-plugin-prometheus_pushgateway: `0.0.2`
- Note that Fluentd has multi-process workers enabled

**Comment by raviepgithub** [comment]
I'm also facing similar issue. Is this working fine for you now?

**Comment by Watson1978** [comment]
Thank you for reporting this issue. T
he behavior you are seeing is actually caused by a timeout during the internal aggregation process.

When you hit `/aggregated_metrics`, the plugin makes sequential HTTP GET requests to each of your 6 workers to collect and concatenate their metrics into one massive string. Because you have many plugins and multiple workers, this synchronous aggregation takes a significant amount of time. If it exceeds the internal HTTP server's timeout, the connection is forcefully closed while the data is still being streamed back to curl or Prometheus, resulting in the output being abruptly cut off mid-line.

For heavy environments with many metrics and multiple workers, using `/aggregated_metrics` might be an anti-pattern because it creates a performance bottleneck.
Instead, you should let Prometheus do what it does best: scrape each worker in parallel.

Please configure your prometheus.yml to scrape all worker ports directly, like this:

```
scrape_configs:
  - job_name: 'fluentd-workers'
    metrics_path: '/metrics'
    static_configs:
      # List all ports for your 6 workers (base_port + worker_id)
      - targets: 
        - 'localhost:24240' # Worker 0
        - 'localhost:24241' # Worker 1
        - 'localhost:24242' # Worker 2
        - 'localhost:24243' # Worker 3
        - 'localhost:24244' # Worker 4
        - 'localhost:24245' # Worker 5
```

Since this is an architectural limitation of the aggregation feature rather than a bug, I will close this issue. 
I hope this helps you set up a stable monitoring environment!
